//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JD_BebidasProjeto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTRADA()
        {
            this.ITENSENTRADA = new HashSet<ITENSENTRADA>();
        }
    
        public int ENTID { get; set; }
        public System.DateTime ENTDATA { get; set; }
        public string ENTORIGEM { get; set; }
        public string ENTOBSERVACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITENSENTRADA> ITENSENTRADA { get; set; }
    }
}
