//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JD_BebidasProjeto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITENSENTRADA
    {
        public int ITEID { get; set; }
        public int PTID { get; set; }
        public int ITEQUANTIDADE { get; set; }
        public decimal ITEPRECO { get; set; }
        public Nullable<decimal> ITETOTAL { get; set; }
        public int ENTID { get; set; }
    
        public virtual ENTRADA ENTRADA { get; set; }
        public virtual PROTIPO PROTIPO { get; set; }
    }
}
