//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JD_BebidasProjeto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITENSSAIDA
    {
        public int ITSID { get; set; }
        public int PTID { get; set; }
        public int ITSQUANTIDADE { get; set; }
        public decimal ITSPRECO { get; set; }
        public Nullable<decimal> ITSTOTAL { get; set; }
        public int SAIID { get; set; }
    
        public virtual SAIDA SAIDA { get; set; }
        public virtual PROTIPO PROTIPO { get; set; }
    }
}
