//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JD_BebidasProjeto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROTIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROTIPO()
        {
            this.ITENSENTRADA = new HashSet<ITENSENTRADA>();
            this.ITENSSAIDA = new HashSet<ITENSSAIDA>();
        }
    
        public int PTID { get; set; }
        public int PROID { get; set; }
        public int TIPID { get; set; }
        public int PTMINIMO { get; set; }
        public int PTMAXIMO { get; set; }
        public int PTESTOQUE { get; set; }
        public byte[] PTIMAGEM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITENSENTRADA> ITENSENTRADA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITENSSAIDA> ITENSSAIDA { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual TIPO TIPO { get; set; }
    }
}
