use master
go
Create DataBase BDJDBEBIDAS
go
use BDJDBEBIDAS
go
Create table ENTRADA(
ENTID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ENTDATA DATETIME DEFAULT GETDATE() NOT NULL,
ENTORIGEM VARCHAR(100) NULL,
ENTOBSERVACAO VARCHAR(200) NULL
)
GO


CREATE TABLE CATEGORIA(
CATID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CATDESCRICAO VARCHAR(100) UNIQUE  NOT NULL
)
GO 



CREATE TABLE PRODUTO(
PROID INT  IDENTITY(1,1) PRIMARY KEY NOT NULL,
PRODESCRICAO VARCHAR(100) NOT NULL,
CATID INT NOT NULL,
PROIMAGEM  varbinary(max) null,
FOREIGN KEY(CATID) REFERENCES CATEGORIA(CATID)
)
GO



CREATE TABLE TIPO(
TIPID INT  IDENTITY(1,1) PRIMARY KEY NOT NULL,
TIPNOME VARCHAR(100) UNIQUE NOT NULL
)

GO
CREATE TABLE PROTIPO(
PTID INT  IDENTITY(1,1) PRIMARY KEY NOT NULL,
PROID INT NOT NULL,
TIPID INT NOT NULL,
PTMINIMO INT  CHECK(PTMINIMO>=0)DEFAULT 0 NOT NULL,
PTMAXIMO INT  CHECK(PTMAXIMO>=0) DEFAULT 0 NOT  NULL,
PTESTOQUE INT  CHECK(PTESTOQUE>=0) DEFAULT 0 NOT NULL,
PTIMAGEM  varbinary(max) null,
FOREIGN KEY(PROID) REFERENCES PRODUTO(PROID),
FOREIGN KEY(TIPID) REFERENCES TIPO(TIPID)
)
GO 

CREATE TABLE ITENSENTRADA(
ITEID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PTID INT NOT NULL,
ITEQUANTIDADE INT CHECK(ITEQUANTIDADE>0) NOT NULL,
ITEPRECO NUMERIC(18,2) CHECK(ITEPRECO>0) NOT NULL,
ITETOTAL AS ITEQUANTIDADE*ITEPRECO,
ENTID INT NOT NULL,
FOREIGN KEY(PTID) REFERENCES PROTIPO(PTID),
FOREIGN KEY(ENTID) REFERENCES ENTRADA(ENTID),

) 
GO

CREATE TABLE SAIDA(
SAIID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
SAIDATA DATETIME DEFAULT GETDATE()
)
go

CREATE TABLE ITENSSAIDA(
ITSID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PTID INT NOT NULL,
ITSQUANTIDADE INT CHECK(ITSQUANTIDADE>0) NOT NULL,
ITSPRECO NUMERIC(18,2) CHECK(ITSPRECO>0) NOT NULL,
ITSTOTAL AS ITSQUANTIDADE*ITSPRECO,
SAIID INT NOT NULL,
FOREIGN KEY(PTID) REFERENCES PROTIPO(PTID),
FOREIGN KEY(SAIID) REFERENCES SAIDA(SAIID)
)





